### PR TITLE
Wait for async processing to finish

### PR DESCRIPTION
**Pull request by kanongil**
Fixes some files not being converted. For instance I observed a '.png' file that was not actually processed.

### CODE REVIEW

**Comment by kanongil** [comment]
Ping? Any chance that this (or something to similar effect) can be merged? Or is the project dead?

**Comment by Xulai** [comment]
Sorry It took so long for me to see this! I've been pretty inactive recently.

**Comment by kanongil** [comment]
@Xulai Can I get you to push a new release on npm?

**Comment by Xulai** [comment]
Published on npm as v0.2.0

**Pull request merged**
